# Generated by Django 4.2 on 2023-05-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakesoft_app', '0002_categoria_cliente_factura_producto_venta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id',
            new_name='documento',
        ),
    ]
