# Generated by Django 4.2 on 2023-05-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesoft_app', '0003_rename_id_cliente_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='documento',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rol',
            field=models.CharField(default='usuario', max_length=50),
        ),
    ]
