# Generated by Django 4.2 on 2023-05-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesoft_app', '0004_rename_documento_cliente_id_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
    ]
