# Generated by Django 4.2 on 2023-05-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesoft_app', '0005_alter_cliente_correo_alter_cliente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
